spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        enabled: true

  application:
    name: openfeign-service

server:
  port: 8090
management:
  endpoints:
    web:
      exposure:
        include: '*'
    enabled-by-default: true