spring:
  application:
    name: sentinel-sample
  cloud:
    sentinel:
      transport:
        port: 8719
        dashboard: localhost:7080
feign:
  sentinel:
    enabled: true
server:
  port: 8080


management:
  endpoints:
    web:
      exposure:
        include: '*'
    enabled-by-default: true