spring:
  cloud:
    nacos:
      discovery:
        enabled: true
        server-addr: 10.120.24.107:8848
        endpoint:
  application:
    name: nacos-consumer-sample
server:
  port: 8082
#management:
#  server:
#    port: 8527
#  endpoints:
#    web:
#      exposure:
#        include: '*'
#    enabled-by-default: true

logging:
  level:
    com.netflix.loadbalancer: debug

