spring:
  cloud:
    nacos:
      discovery:
        enabled: true
        server-addr: 127.0.0.1:8848
  application:
    name: nacos-consumer-sample
server:
  port: 8082
management:
  endpoints:
    web:
      exposure:
        include: '*'
    enabled-by-default: true

